apiVersion: v1
kind: Service
metadata:
  name: {{ include "bdc.fullname" . }}-web
  labels:
    {{- include "bdc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bdc.web.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bdc.fullname" . }}-backend
  labels:
    {{- include "bdc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bdc.backend.selectorLabels" . | nindent 4 }}
